# Generated by Django 4.0.5 on 2022-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoscr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor'),
        ),
    ]
