# Generated by Django 4.0.5 on 2022-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoscr', '0003_libro_editorial_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='año',
            field=models.DateField(max_length=25, null=True, verbose_name='Año'),
        ),
    ]
